
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationjobs/finalizers
  verbs:
  - update
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationschedulers/finalizers
  verbs:
  - update
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationschedulers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationtasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationtasks/finalizers
  verbs:
  - update
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationtasks/status
  verbs:
  - get
  - patch
  - update
