# permissions for end users to view tuplegenerationschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuplegenerationscheduler-viewer-role
rules:
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationschedulers/status
  verbs:
  - get
