# permissions for end users to edit tuplegenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuplegenerator-editor-role
rules:
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerators/status
  verbs:
  - get
