# permissions for end users to view tuplegenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuplegenerator-viewer-role
rules:
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerators/status
  verbs:
  - get
