# permissions for end users to view tuplegenerationjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuplegenerationjob-viewer-role
rules:
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - klyshko.carbnyestack.io
  resources:
  - tuplegenerationjobs/status
  verbs:
  - get
