apiVersion: klyshko.carbnyestack.io/v1alpha1
kind: TupleGenerationJob
metadata:
  name: tuplegenerationjob-sample
spec:
  id: 2351d9aa-352a-4730-babc-538095744538
  type: multiplicationtriple_gfp
  count: 100000
