#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: klyshko.carbnyestack.io/v1alpha1
kind: TupleGenerationJob
metadata:
  name: tuplegenerationjob-sample
spec:
  id: 9fc7f5b7-09d9-4c62-97c7-2d7eeddfb858
  type: MULTIPLICATION_TRIPLE_GFP
  count: 10000
