#
# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: klyshko.carbnyestack.io/v1alpha1
kind: TupleGenerationScheduler
metadata:
  name: tuplegenerationscheduler-sample
spec:
  concurrency: 2
  threshold: 1000000
  tuplesPerJob: 100000
  generator:
    image: carbynestack/klyshko-mp-spdz:1.0.0-SNAPSHOT
    imagePullPolicy: IfNotPresent
