apiVersion: klyshko.carbnyestack.io/v1alpha1
kind: TupleGenerationJob
metadata:
  name: tuplegenerationjob-sample
spec:
  id: b8caa9c3-e0a9-4567-ae15-553a71b9464e
  type: multiplicationtriple_gfp
  count: 100000
