#
# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: klyshko.carbnyestack.io/v1alpha1
kind: TupleGenerator
metadata:
  name: mp-spdz-lowgear
spec:
  image: carbynestack/klyshko-mp-spdz:1.0.0-SNAPSHOT
  imagePullPolicy: IfNotPresent
  supports:
    - type: BIT_GFP
      batchSize: 10000
    - type: INPUT_MASK_GFP
      batchSize: 10000
    - type: INVERSE_TUPLE_GFP
      batchSize: 10000
    - type: SQUARE_TUPLE_GFP
      batchSize: 10000
    - type: MULTIPLICATION_TRIPLE_GFP
      batchSize: 1000
    - type: BIT_GF2N
      batchSize: 1000
    - type: INPUT_MASK_GF2N
      batchSize: 1000
    - type: INVERSE_TUPLE_GF2N
      batchSize: 1000
    - type: SQUARE_TUPLE_GF2N
      batchSize: 1000
    - type: MULTIPLICATION_TRIPLE_GF2N
      batchSize: 1000
