#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v2
name: klyshko-operator
description: A Helm chart for the Carbyne Stack Klyshko Operator
type: application
version: 0.1.0
appVersion: "0.1.0"
