#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#

init:
	ln -s -f ../../cowgear-offline.cpp MP-SPDZ/Utils/cowgear-offline.cpp
	ln -s -f ../CONFIG.mine MP-SPDZ/CONFIG.mine
	cat Makefile.rules >> MP-SPDZ/Makefile
