#
# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: klyshko-controller-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: klyshko-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: klyshko-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: klyshko-leader-election-role
subjects:
  - kind: ServiceAccount
    name: klyshko-controller-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: klyshko-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationjobs/finalizers
    verbs:
      - update
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationjobs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationschedulers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationschedulers/finalizers
    verbs:
      - update
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationschedulers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationtasks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationtasks/finalizers
    verbs:
      - update
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerationtasks/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerators
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - klyshko.carbnyestack.io
    resources:
      - tuplegenerators/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klyshko-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: klyshko-manager-role
subjects:
  - kind: ServiceAccount
    name: klyshko-controller-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klyshko-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klyshko-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klyshko-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: klyshko-proxy-role
subjects:
  - kind: ServiceAccount
    name: klyshko-controller-manager
    namespace: {{ .Release.Namespace }}
