#
# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#


# This file defines the default values for all variables used in the Klyshko Operator Helm Chart.

imagePullSecrets: []

controller:
  image:
    registry: ghcr.io
    repository: carbynestack/klyshko-operator-controller
    pullPolicy: IfNotPresent
    tag: latest
  etcdEndpoint: 172.18.1.129:2379

provisioner:
  image:
    registry: ghcr.io
    repository: carbynestack/klyshko-provisioner
    tag: latest
