#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Build and test MP-SPDZ CowGear CRG
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: carbynestack/klyshko-mp-spdz-cowgear
  WORKING_DIRECTORY: klyshko-mp-spdz-cowgear
jobs:
  changes:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    outputs:
      mp-spdz-cowgear: ${{ steps.filter.outputs.mp-spdz-cowgear }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check whether MP-SPDZ CowGear codebase is affected
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            mp-spdz-cowgear:
              - '${{ env.WORKING_DIRECTORY }}/**'
  mp-spdz-cowgear-test:
    runs-on: ubuntu-22.04
    needs: changes
    if: ${{ needs.changes.outputs.mp-spdz-cowgear == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.WORKING_DIRECTORY }}
          file: ${{ env.WORKING_DIRECTORY }}/Dockerfile
          push: false
          tags: latest
      - name: Test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          cd test
          bats/bin/bats roundtrip.bats
  # This is required to allow for setting the test job as required in scenarios
  # where the tests are not actually run, e.g., when there are no changes to
  # the relevant codebase
  mp-spdz-cowgear-test-status:
    runs-on: ubuntu-22.04
    needs: mp-spdz-cowgear-test
    if: '!cancelled()' # Makes the job run regardless whether 'mp-spdz-cowgear-test' succeeds or not but allows for cancellation
    steps:
      - name: Tests successful
        if: ${{ !(contains(needs.mp-spdz-cowgear-test.result, 'failure')) }}
        run: exit 0
      - name: Tests failed
        if: ${{ contains(needs.mp-spdz-cowgear-test.result, 'failure') }}
        run: exit 1
