#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/carbynestack/klyshko.
#
# SPDX-License-Identifier: Apache-2.0
#
name: Build and publish Operator
on:
  workflow_dispatch:
  push:
defaults:
  run:
    working-directory: klyshko-operator
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: carbynestack/klyshko-operator-controller
  WORKING_DIRECTORY: klyshko-operator
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16'
      - name: Setup Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build and Test
        run: |
          make test
      - name: Publishing Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.WORKING_DIRECTORY }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Configure Helm Chart
        run: |
          VERSION=$(sed -n 's/version: \(.*\)/\1/p' charts/klyshko-operator/Chart.yaml)-${{ steps.meta.outputs.version }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          sed -i 's/version: \(.*\)/version: '"$VERSION"'/g' charts/klyshko-operator/Chart.yaml
          sed -i 's/tag: latest/tag: ${{ steps.meta.outputs.version }}/g' charts/klyshko-operator/values.yaml
      - name: Push Helm Chart
        uses: appany/helm-oci-chart-releaser@v0.4.0
        with:
          name: klyshko-operator
          repository: carbynestack
          tag: ${{ env.VERSION }}
          path: klyshko-operator/charts/klyshko-operator
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
